apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  ports:
  - name: management
    port: 7070
    targetPort: 8080
    protocol: TCP
  selector:
    app: analytics
---
apiVersion: v1
kind: Service
metadata:
  name: events
  labels:
    app: events
spec:
  ports:
  - name: input
    port: 5555
    targetPort: 5555
    protocol: TCP
  selector:
    app: analytics
---
apiVersion: v1
kind: Service
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  ports:
  - name: publisher
    port: 5556
    targetPort: 5556
    protocol: TCP
  selector:
    app: analytics
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
  - port: 9042
    targetPort: 9042
    protocol: TCP
  selector:
    app: cassandra
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: cybermon
  labels:
    app: cybermon
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: cybermon
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
  selector:
    app: kibana
---
apiVersion: v1
kind: Service
metadata:
  name: sparql
  labels:
    app: sparql
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: sparql
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: url-classifier
  labels:
    app: url-classifier
spec:
  ports:
  - name: host-classifier
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: url-classifier
---
apiVersion: v1
kind: Service
metadata:
  name: vpn
  labels:
    app: vpn
spec:
  ports:
  - name: vpn
    port: 1194
    targetPort: 1194
    protocol: UDP
  selector:
    app: vpn-server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: gaffer
  labels:
    app: gaffer
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: wildfly
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop0000
  labels:
    app: hadoop0000
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: hadoop0000
---
apiVersion: v1
kind: Service
metadata:
  name: zk1
  labels:
    app: zk1
spec:
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: rpc
  - port: 2888
    targetPort: 2888
    protocol: TCP
    name: internal1
  - port: 3888
    targetPort: 3888
    protocol: TCP
    name: internal2
  selector:
    app: zk1
---
apiVersion: v1
kind: Service
metadata:
  name: zk2
  labels:
    app: zk2
spec:
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: rpc
  - port: 2888
    targetPort: 2888
    protocol: TCP
    name: internal1
  - port: 3888
    targetPort: 3888
    protocol: TCP
    name: internal2
  selector:
    app: zk2
---
apiVersion: v1
kind: Service
metadata:
  name: zk3
  labels:
    app: zk3
spec:
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: rpc
  - port: 2888
    targetPort: 2888
    protocol: TCP
    name: internal1
  - port: 3888
    targetPort: 3888
    protocol: TCP
    name: internal2
  selector:
    app: zk3
---
apiVersion: v1
kind: Service
metadata:
  name: accumulo0000
  labels:
    app: accumulo0000
spec:
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP
    name: master
  - port: 50091
    targetPort: 50091
    protocol: TCP
    name: gc
  - port: 9995
    targetPort: 9995
    protocol: TCP
    name: monitor
  - port: 12234
    targetPort: 12234
    protocol: TCP
    name: tracer
  - port: 42424
    targetPort: 42424
    protocol: TCP
    name: proxy
  - port: 10002
    targetPort: 10002
    protocol: TCP
    name: slave
  - port: 10001
    targetPort: 10001
    protocol: TCP
    name: replication
  selector:
    app: accumulo0000
