apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: analytics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: gcr.io/trust-networks/analytics:0.69
        livenessProbe:
          exec:
            command:
            - wye-get-health
          initialDelaySeconds: 15
          timeoutSeconds: 10
        resources:
          requests:
            memory: "512M"
            cpu: "1.0"
          limits:
            memory: "1024M"
            cpu: "1.0"
        volumeMounts:
        - mountPath: /key
          name: keys
          readOnly: True
        - mountPath: /curve-public
          name: analytics-curve-client-keys
          readOnly: True
        - mountPath: /curve-private
          name: analytics-curve-publisher-private
          readOnly: True
        env:
        - name: KEY
          value: /key/private.json
        - name: CURVE_PUBLIC
          value: /curve-public
        - name: CURVE_PRIVATE
          value: /curve-private
        - name: BIGQUERY_PROJECT
          value: trust-networks
        - name: BIGQUERY_DATASET
          value: cyberprobe
        - name: RAW_TABLE
          value: cyberprobe
        - name: ACTIVITY_TABLE
          value: activity
        - name: TRUST_TABLE
          value: fingerprint
        - name: URI_TABLE
          value: uri_classification
        - name: CASSANDRA_KEYSPACE
          value: rdf
        - name: CASSANDRA_CONTACTS
          value: '["cassandra"]'
        - name: ELASTICSEARCH_INDEX
          value: cyberprobe
        - name: ELASTICSEARCH_OBJECT
          value: observation
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        - name: GAFFER_URL
          value: http://gaffer:8080/rest/v1
        ports:
        - containerPort: 8080
          name: management
        - containerPort: 5555
          name: input
        - containerPort: 5556
          name: publisher
      volumes:
      - name: keys
        secret:
          secretName: keys
      - name: analytics-curve-client-keys
        secret:
          secretName: analytics-curve-client-keys
      - name: analytics-curve-publisher-private
        secret:
          secretName: analytics-curve-publisher-private
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:3.9
        resources:
          requests:
            memory: "4096M"
            cpu: "1.0"
          limits:
            memory: "8192M"
            cpu: "2.0"
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        volumeMounts:
          - mountPath: /var/lib/cassandra
            name: cassandra-data
      volumes:
      - name: cassandra-data
        gcePersistentDisk:
          pdName: cassandra-0000
          fsType: ext4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:5.0.0
        resources:
          requests:
            memory: "4096M"
            cpu: "1.0"
          limits:
            memory: "4096M"
            cpu: "1.0"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: http2
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-data
      - name: sysctl-sidecar
        image: alpine
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args:
          - -c
          - sysctl -w vm.max_map_count=524288 && while true; do sleep 1000000; done
      volumes:
      - name: elasticsearch-data
        gcePersistentDisk:
          pdName: elasticsearch-0000
          fsType: ext4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cybermon
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: cybermon
    spec:
      containers:
      - name: cybermon
        image: cybermaggedon/cybermon:0.77
        resources:
          requests:
            memory: "128M"
            cpu: "0.2"
          limits:
            memory: "1024M"
            cpu: "1.0"
        env:
        - name: ZMQ_CONNECT
          value: tcp://events:5555
        ports:
        - containerPort: 9000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:5.0.0
        command: ["/bin/sh"]
        args:
          - -c
          - "echo server.basePath: /kibana >> /etc/kibana/kibana.yml; /docker-entrypoint.sh kibana"
        resources:
          requests:
            memory: "1024M"
            cpu: "0.2"
          limits:
            memory: "2048M"
            cpu: "0.5"
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sparql
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: sparql
    spec:
      containers:
      - name: sparql
        image: cybermaggedon/sparql-cassandra:0.04a
        command:
        - "sparql"
        - "8081"
        - "cassandra"
        - "cassandra"
        resources:
          requests:
            memory: "64M"
            cpu: "0.2"
          limits:
            memory: "256M"
            cpu: "0.5"
        ports:
        - containerPort: 8081
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: gcr.io/trust-networks/web:0.42
        resources:
          requests:
            memory: "64M"
            cpu: "0.1"
          limits:
            memory: "256M"
            cpu: "0.5"
        ports:
        - containerPort: 443
          name: https
        - containerPort: 8099
          name: http
        volumeMounts:
        - mountPath: /cert
          name: web-cert
          readOnly: True
      volumes:
      - name: web-cert
        secret:
          secretName: web-cert
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ca
    spec:
      containers:
      - name: ca
        image: gcr.io/trust-networks/ca:0.11
        resources:
          requests:
            memory: "64M"
            cpu: "0.1"
          limits:
            memory: "64M"
            cpu: "0.5"
        volumeMounts:
        - mountPath: /cert
          name: ca-cert
          readOnly: True
        - mountPath: /ca
          name: ca-data
        env:
        - name: CA
          value: /ca
        - name: CA_CERT
          value: /cert
      volumes:
      - name: ca-cert
        secret:
          secretName: ca-cert
      - name: ca-data
        gcePersistentDisk:
          pdName: ca-0000
          fsType: ext4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: url-classifier
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: url-classifier
    spec:
      containers:
      - name: ca
        image: gcr.io/trust-networks/url-classifier:0.01
        resources:
          requests:
            memory: "512M"
            cpu: "0.1"
          limits:
            memory: "512M"
            cpu: "0.5"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vpn-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vpn-server
    spec:
      containers:
      - name: vpn-server
        image: gcr.io/trust-networks/vpn-server:0.27
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            memory: "256M"
            cpu: "0.2"
          limits:
            memory: "256M"
            cpu: "0.5"
        volumeMounts:
        - mountPath: /key
          name: vpn-server-key
          readOnly: True
      volumes:
      - name: vpn-server-key
        secret:
          secretName: vpn-server-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vpn-ca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vpn-ca
    spec:
      containers:
      - name: vpn-ca
        image: gcr.io/trust-networks/vpn-ca:0.21
        resources:
          requests:
            memory: "64M"
            cpu: "0.2"
          limits:
            memory: "64M"
            cpu: "0.5"
        volumeMounts:
        - mountPath: /key
          name: vpn-ca-key
          readOnly: True
        - mountPath: /ca
          name: vpn-ca-data
        env:
        - name: CA_CERT
          value: /key
        - name: CA
          value: /ca
      volumes:
      - name: vpn-ca-key
        secret:
          secretName: vpn-ca-key
      - name: vpn-ca-data
        gcePersistentDisk:
          pdName: vpn-ca-data-0000
          fsType: ext4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hadoop0000
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hadoop0000
        system: gaffer
    spec:
      containers:
      - name: hadoop
        image: cybermaggedon/hadoop:latest
        resources:
          requests:
            memory: "1024M"
            cpu: "1.0"
          limits:
            memory: "1024M"
            cpu: "1.0"
        ports:
        - containerPort: 50070
          name: namenode-http
        - containerPort: 50075
          name: datanode
        - containerPort: 9000
          name: namenode-rpc
        volumeMounts:
          - mountPath: /data
            name: hadoop
        env:
        - name: DAEMONS
          value: namenode,secondarynamenode,datanode
      volumes:
      - name: hadoop
        gcePersistentDisk:
          pdName: hadoop-0000
          fsType: ext4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zk1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zk1
        system: gaffer
    spec:
      containers:
      - name: zookeeper
        image: cybermaggedon/zookeeper:3.4.9b
        resources:
          requests:
            memory: "512M"
            cpu: "0.3"
          limits:
            memory: "512M"
            cpu: "0.3"
        ports:
        - containerPort: 2888
          name: internal1
        - containerPort: 3888
          name: internal2
        - containerPort: 2181
          name: service
        volumeMounts:
          - mountPath: /data
            name: zookeeper
        env:
        - name: ZOOKEEPERS
          value: zk1,zk2,zk3
        - name: ZOOKEEPER_MYID
          value: "1"
      volumes:
      - name: zookeeper
        gcePersistentDisk:
          pdName: zookeeper-1
          fsType: ext4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zk2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zk2
        system: gaffer
    spec:
      containers:
      - name: zookeeper
        image: cybermaggedon/zookeeper:3.4.9b
        resources:
          requests:
            memory: "512M"
            cpu: "0.3"
          limits:
            memory: "512M"
            cpu: "0.3"
        ports:
        - containerPort: 2888
          name: internal1
        - containerPort: 3888
          name: internal2
        - containerPort: 2181
          name: service
        volumeMounts:
          - mountPath: /data
            name: zookeeper
        env:
        - name: ZOOKEEPERS
          value: zk1,zk2,zk3
        - name: ZOOKEEPER_MYID
          value: "2"
      volumes:
      - name: zookeeper
        gcePersistentDisk:
          pdName: zookeeper-2
          fsType: ext4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zk3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zk3
        system: gaffer
    spec:
      containers:
      - name: zookeeper
        image: cybermaggedon/zookeeper:3.4.9b
        resources:
          requests:
            memory: "512M"
            cpu: "0.3"
          limits:
            memory: "512M"
            cpu: "0.3"
        ports:
        - containerPort: 2888
          name: internal1
        - containerPort: 3888
          name: internal2
        - containerPort: 2181
          name: service
        volumeMounts:
          - mountPath: /data
            name: zookeeper
        env:
        - name: ZOOKEEPERS
          value: zk1,zk2,zk3
        - name: ZOOKEEPER_MYID
          value: "3"
      volumes:
      - name: zookeeper
        gcePersistentDisk:
          pdName: zookeeper-3
          fsType: ext4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accumulo0000
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: accumulo0000
        system: gaffer
    spec:
      containers:
      - name: accumulo
        image: cybermaggedon/accumulo-gaffer:0.4.4g
        resources:
          requests:
            memory: "2G"
            cpu: "1.0"
          limits:
            memory: "2G"
            cpu: "1.0"
        ports:
        - containerPort: 9999
          name: master
        - containerPort: 9997
          name: tablet-server
        - containerPort: 50091
          name: gc
        - containerPort: 9995
          name: monitor
        - containerPort: 4560
          name: monitor-log
        - containerPort: 12234
          name: tracer
        - containerPort: 42424
          name: proxy
        - containerPort: 10002
          name: slave
        - containerPort: 10001
          name: replication
        env:
        - name: ZOOKEEPERS
          value: zk1,zk2,zk3
        - name: MY_HOSTNAME
          value: MY_IP
        - name: GC_HOSTS
          value: MY_IP
        - name: MASTER_HOSTS
          value: MY_IP
        - name: SLAVE_HOSTS
          value: MY_IP
        - name: MONITOR_HOSTS
          value: MY_IP
        - name: TRACER_HOSTS
          value: MY_IP
        - name: HDFS_VOLUMES
          value: hdfs://hadoop0000:9000/accumulo
        - name: MEMORY_MAPS_MAX
          value: 300M
        - name: CACHE_DATA_SIZE
          value: 30M
        - name: CACHE_INDEX_SIZE
          value: 40M
        - name: SORT_BUFFER_SIZE
          value: 50M
        - name: WALOG_MAX_SIZE
          value: 512M
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wildfly
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wildfly
        system: gaffer
    spec:
      containers:
      - name: accumulo
        image: gcr.io/trust-networks/gaffer:0.4.4g
        resources:
          requests:
            memory: "1.0G"
            cpu: "0.5"
          limits:
            memory: "1.0G"
            cpu: "0.5"
        ports:
        - containerPort: 8080
          name: rest
        env:
        - name: ZOOKEEPERS
          value: zk1,zk2,zk3
