apiVersion: v1
kind: Service
metadata:
  name: vpn
  labels:
    app: vpn
spec:
  ports:
  - name: vpn
    port: 1194
    targetPort: 1194
    protocol: UDP
  selector:
    app: vpn-server
  type: LoadBalancer
