#!/usr/bin/env python

# This is some demo code, shows how to connect to the analytics subscriber.
# You will need a client pub/priv pair, and the server's public key.

import zmq
import zmq.auth
from zmq.auth.thread import ThreadAuthenticator

ctx = zmq.Context.instance()

client = ctx.socket(zmq.SUB)
client.setsockopt(zmq.SUBSCRIBE, "")

# We need two certificates, one for the client and one for
# the server. The client must know the server's public key
# to make a CURVE connection.
client_secret_file = "curve/dev-client.key_secret"
client_public, client_secret = zmq.auth.load_certificate(client_secret_file)
client.curve_secretkey = client_secret
client.curve_publickey = client_public

server_public_file = "curve/publisher.key"
server_public, _ = zmq.auth.load_certificate(server_public_file)
# The client must know the server's public key to make a CURVE connection.
client.curve_serverkey = server_public
client.connect('tcp://104.196.159.232:5556')

# Dump out all messages.
while True:
    msg = client.recv()
    print msg

