#!/bin/bash

if [ $# -ne 2 ]
then
    echo 'Usage:' 1>&2
    echo '  create "Full Name" full.name@trustnetworks.com' 1>&2
    exit 1
fi

ca=${CA:-.}
ca_cert=${CA_CERT:-.}

# Create a randomish password.
PASSWORD=$(uuidgen | cut -d- -f1)

# RSA key size.
KEY_SIZE=4096

# Random generation parameters.
RAND_COUNT=128
RAND_BLOCK=32
RANDOM_DEVICE=/dev/urandom
DD="dd iflag=fullblock"

# Certificates valid for 2 years.
CERT_VALIDITY=710

# Temporary files.
RAND_FILE=${ca}/rand.user$$
KEY_FILE=${ca}/key.user$$
REQ_FILE=${ca}/req.user$$
CONFIG_FILE=${ca}/config.user$$

# Output files.
CERT_FILE=${ca}/cert.user$$
PKG_FILE=${ca}/pkg.user$$

# Create config file

name=$1
email=$2

cat <<EOT >> ${CONFIG_FILE}
[req]
distinguished_name=dn
prompt=no

[dn]
commonName=${name}
organizationalUnitName=Users
organizationName=Trust Networks
emailAddress=${email}
EOT

# Create random data.
echo '**** Create random data...'
${DD} bs=${RAND_BLOCK} count=${RAND_COUNT} if=${RANDOM_DEVICE} of=${RAND_FILE}
if [ $? -ne 0 ]
then
    echo Random creation failed. 1>&2
    exit 1
fi

# Create private key.
echo '**** Generate private key...'
openssl genrsa -out ${KEY_FILE} -rand ${RAND_FILE} ${KEY_SIZE}
if [ $? -ne 0 ]
then
    echo Private key generation failed. 1>&2
    exit 1
fi

# Discard random.
rm -f ${RAND_FILE}

# Create certificate request.
echo '**** Generate certificate request...'
openssl req -key ${KEY_FILE} -out ${REQ_FILE} -new \
	-config ${CONFIG_FILE}
if [ $? -ne 0 ]
then
    echo Certificate request creation failed. 1>&2
    exit 1
fi

rm -f ${CONFIG_FILE}

echo '**** Signing request...'
# Sign certificate request to create certificate.
openssl x509 -req -in ${REQ_FILE} -CAkey ${ca_cert}/key.ca \
	-CA ${ca_cert}/cert.ca -CAcreateserial -CAserial ${ca}/serial \
	-out ${CERT_FILE} -days ${CERT_VALIDITY}
#	-addtrust clientAuth
if [ $? -ne 0 ]
then
    echo Certificate signing failed. 1>&2
    exit 1
fi

# Delete request.
rm -f ${REQ_FILE}

# Verify.
echo '**** Verify certificate...'
openssl verify -CAfile ${ca_cert}/cert.ca ${CERT_FILE}
if [ $? -ne 0 ]
then
    echo Certificate verification failed. 1>&2
    exit 1
fi

# Create PKCS12 package.
echo '**** Create key/certificate package...'
openssl pkcs12 -export -passout pass:${PASSWORD} -inkey ${KEY_FILE} \
	-in ${CERT_FILE} -caname 'Trust Networks' \
	-certfile ${ca_cert}/cert.ca -out ${PKG_FILE}
if [ $? -ne 0 ]
then
    echo Package creation failed. 1>&2
    exit 1
fi

(
    openssl x509 -in ${CERT_FILE}  -noout -serial -email -subject -dates
    echo '----'
) >> ${ca}/register

# Remove stuff not needed.
rm -f ${KEY_FILE}

# This leaves the certificate and the package.  Now, rename them.

# Get certificate serial.
serial=$(openssl x509 -in ${CERT_FILE} -noout -serial | sed 's/serial=//')

mv ${CERT_FILE} cert.${serial}
CERT_FILE=cert.${serial}

mv ${PKG_FILE} pkg.${serial}.p12
PKG_FILE=${serial}.p12

echo '**** All complete.'

echo PKCS12 package is in pkg.${PKG_FILE}.
echo Password is ${PASSWORD}.

