apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  ports:
  - port: 7070
    targetPort: 8080
    protocol: TCP
  selector:
    app: analytics
----
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
  - port: 9642
    targetPort: 9642
    protocol: TCP
  selector:
    app: cassandra
----
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch
----
apiVersion: v1
kind: Service
metadata:
  name: gaffer
  labels:
    app: gaffer
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: gaffer
----
apiVersion: v1
kind: Pod
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  containers:
  - name: analytics
    image: gcr.io/trust-networks/analytics:mvp2a
    volumeMounts:
    - name: keys
      mountPath: /wye/key
      readOnly: True
    env:
    - name: KEY
      value: /wye/key/private.json
    - name: BIGQUERY_PROJECT
      value: trust-networks
    - name: BIGQUERY_DATASET
      value: cyberprobe
    - name: RAW_TABLE
      value: cyberprobe2
    - name: ACTIVITY_TABLE
      value: activity2
    - name: TRUST_TABLE
      value: fingerprint2
    - name: CASSANDRA_KEYSPACE
      value: rdf
    - name: CASSANDRA_CONTACTS
      value: '["cassandra"]'
    - name: CYBERMON_BINDING
      value: tcp://10.142.0.2:5555
    - name: ELASTICSEARCH_INDEX
      value: cyberprobe
    - name: ELASTICSEARCH_OBJECT
      value: observation
    - name: ELASTICSEARCH_URL
      value: http://elasticsearch:9200
    - name: GAFFER_URL
      value: http://gaffer:8080/example-rest/v1
    ports:
    - containerPort: 8080
  volumes:
  - name: keys
    secret:
      secretName: keys
----
apiVersion: v1
kind: Pod
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  containers:
  - name: cassandra
    image: cassandra:3.7
    ports:
    - containerPort: 7000
      name: intra-node
    - containerPort: 7001
      name: tls-intra-node
    - containerPort: 7199
      name: jmx
    - containerPort: 9642
      name: cql
    volumeMounts:
      - mountPath: /var/lib/cassandra
        name: cassandra-data
  volumes:
  - name: cassandra-data
    emptyDir: {}
----
apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  containers:
  - name: elasticsearch
    image: elasticsearch:2.3.5
    ports:
    - containerPort: 9200
      name: http
    - containerPort: 9300
      name: http2
    volumeMounts:
      - mountPath: /usr/share/elasticsearch/data
        name: elasticsearch-data
  volumes:
  - name: elasticsearch-data
    emptyDir: {}
----
apiVersion: v1
kind: Pod
metadata:
  name: gaffer
  labels:
    app: gaffer
spec:
  containers:
  - name: gaffer
    image: cybermaggedon/gaffer:0.3.9
    ports:
    - containerPort: 8080
    volumeMounts:
      - mountPath: /data
        name: gaffer-data
  volumes:
  - name: gaffer-data
    emptyDir: {}
