apiVersion: v1
kind: Pod
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  containers:
  - name: analytics
    image: gcr.io/trust-networks/analytics:0.01a
    volumeMounts:
    - name: keys
      mountPath: /wye/key
      readOnly: True
    env:
    - name: KEY
      value: /wye/key/private.json
    - name: BIGQUERY_PROJECT
      value: trust-networks
    - name: BIGQUERY_DATASET
      value: cyberprobe
    - name: RAW_TABLE
      value: cyberprobe2
    - name: ACTIVITY_TABLE
      value: activity2
    - name: TRUST_TABLE
      value: fingerprint2
    - name: CASSANDRA_KEYSPACE
      value: rdf
    - name: CASSANDRA_CONTACTS
      value: "['127.0.0.1']"
    - name: CYBERMON_BINDING
      value: tcp://localhost:5555
    - name: ELASTICSEARCH_INDEX
      value: cyberprobe
    - name: ELASTICSEARCH_OBJECT
      value: observation
    - name: ELASTICSEARCH_URL
      value: http://elasticsearch:9200
    - name: GAFFER_URL
      value: http://gaffer:8080/example-rest/v1
    ports:
    - containerPort: 8080
  volumes:
  - name: keys
    secret:
      secretName: keys
