apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  ports:
  - port: 7070
    targetPort: 8080
    protocol: TCP
  selector:
    app: analytics
----
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
  - port: 9642
    targetPort: 9642
    protocol: TCP
  selector:
    app: cassandra
----
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch
----
apiVersion: v1
kind: Service
metadata:
  name: gaffer
  labels:
    app: gaffer
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: gaffer
