FROM nginx:1.11.3
COPY lodlive /usr/share/nginx/html/lodlive/
COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/
COPY linkurious /usr/share/nginx/html/linkurious/
COPY graph.html /usr/share/nginx/html/
EXPOSE 443
