FROM nginx:1.11.3
COPY index.html /usr/share/nginx/html/
COPY lodlive /usr/share/nginx/html/lodlive/
COPY default.conf /etc/nginx/conf.d/default.conf
COPY CERT.web /etc/nginx/CERT.web
COPY KEY.web /etc/nginx/KEY.web
COPY CERT.ca /etc/nginx/CERT.ca

